/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Message {
	char *data;
	char *author;
	int timestamp;
};
typedef struct Message Message;

typedef struct {
	u_int length;
	Message *list;
} Chain;

#define PGRM_CHAT 0xFACE
#define V_CHAT 1

#if defined(__STDC__) || defined(__cplusplus)
#define writeMsg 1
extern  int * writemsg_1(Message *, CLIENT *);
extern  int * writemsg_1_svc(Message *, struct svc_req *);
#define getChat 2
extern  Chain * getchat_1(int *, CLIENT *);
extern  Chain * getchat_1_svc(int *, struct svc_req *);
extern int pgrm_chat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define writeMsg 1
extern  int * writemsg_1();
extern  int * writemsg_1_svc();
#define getChat 2
extern  Chain * getchat_1();
extern  Chain * getchat_1_svc();
extern int pgrm_chat_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Message (XDR *, Message*);
extern  bool_t xdr_Chain (XDR *, Chain*);

#else /* K&R C */
extern bool_t xdr_Message ();
extern bool_t xdr_Chain ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
